import React, { useState, useEffect } from 'react';
import { useToast } from '../../context/ToastContext';
import { getTimetableVersions } from '../../services/timetableService';
import { transitionTimetableVersion } from '../../services/hodAllocationService';
import PageHeader from '../../components/common/PageHeader';
import Breadcrumbs from '../../components/layout/Breadcrumbs';
import Card from '../../components/common/Card';
import Badge from '../../components/common/Badge';
import Button from '../../components/common/Button';
import Spinner from '../../components/common/Spinner';
import ErrorState from '../../components/common/ErrorState';
import EmptyState from '../../components/common/EmptyState';

export default function TimetableApprovalPage() {
  const { showToast } = useToast();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [versions, setVersions] = useState([]);
  const [updatingId, setUpdatingId] = useState(null);

  const loadVersions = async () => {
    try {
      setLoading(true);
      setError(null);
      const res = await getTimetableVersions();
      const list = Array.isArray(res) ? res : res?.data || [];
      setVersions(list);
    } catch (err) {
      console.error('[TimetableApprovalPage] Failed to fetch:', err);
      setError(err.message || 'Unable to load timetable versions.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadVersions();
  }, []);

  const handleTransition = async (versionId, newStatus) => {
    let rejectionReason = null;
    if (newStatus === 'REJECTED') {
      rejectionReason = window.prompt('Provide statutory rejection remarks:');
      if (rejectionReason === null) return;
    }

    try {
      setUpdatingId(versionId);
      await transitionTimetableVersion(versionId, newStatus, rejectionReason);
      showToast(`Timetable version state transitioned to ${newStatus}.`, 'success');
      await loadVersions();
    } catch (err) {
      console.error('[TimetableApprovalPage] State transition failed:', err);
      showToast(err.message || 'Failed to update timetable status.', 'error');
    } finally {
      setUpdatingId(null);
    }
  };

  return (
    <div>
      <PageHeader
        title="Timetable State Ratification"
        description="Formal statutory approval desk for transitioning timetable versions (Pending HOD Approval -> Approved -> Published)."
        breadcrumbs={[
          { label: 'HOD Portal', path: '/hod/dashboard' },
          { label: 'State Ratification' },
        ]}
        badge={<Badge variant="warning">STATUTORY RATIFICATION</Badge>}
        actions={
          <Button variant="outline" size="sm" icon="🔄" onClick={loadVersions}>
            Refresh Versions
          </Button>
        }
      />

      <Card style={{ padding: 0, overflow: 'hidden' }}>
        <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--color-border-subtle)' }}>
          <h3 style={{ margin: 0, fontSize: '1rem', fontWeight: 700, color: 'var(--color-primary)' }}>
            Timetable Versions & Governance Pipeline ({versions.length})
          </h3>
        </div>

        {loading ? (
          <div style={{ padding: '48px 0', textAlign: 'center' }}>
            <Spinner size="md" />
            <div style={{ marginTop: '12px', fontSize: '0.875rem', color: 'var(--color-outline)' }}>
              Loading timetable versions...
            </div>
          </div>
        ) : error ? (
          <div style={{ padding: '24px' }}>
            <ErrorState message={error} onRetry={loadVersions} />
          </div>
        ) : versions.length === 0 ? (
          <div style={{ padding: '32px' }}>
            <EmptyState
              title="No timetable versions recorded"
              description="Coordinators have not submitted any draft timetable versions yet."
            />
          </div>
        ) : (
          <div className="ui-table-scroll-container">
            <table style={{ width: '100%', minWidth: '750px', borderCollapse: 'collapse', fontSize: '0.875rem' }}>
              <thead>
                <tr style={{ backgroundColor: 'var(--color-surface-container-low)', textAlign: 'left', borderBottom: '1px solid var(--color-surface-container)' }}>
                  <th style={{ padding: '12px 16px', fontWeight: 600 }}>Version Label</th>
                  <th style={{ padding: '12px 16px', fontWeight: 600 }}>Academic Year / Term</th>
                  <th style={{ padding: '12px 16px', fontWeight: 600 }}>Cohort</th>
                  <th style={{ padding: '12px 16px', fontWeight: 600 }}>Generated By</th>
                  <th style={{ padding: '12px 16px', fontWeight: 600 }}>Current Status</th>
                  <th style={{ padding: '12px 16px', fontWeight: 600, textAlign: 'right' }}>Executive Actions</th>
                </tr>
              </thead>
              <tbody>
                {versions.map((ver) => {
                  const isUpdating = updatingId === ver._id;
                  return (
                    <tr key={ver._id} style={{ borderBottom: '1px solid var(--color-surface-container)' }}>
                      <td style={{ padding: '12px 16px', fontFamily: 'var(--font-mono)', fontWeight: 700, color: 'var(--color-primary)' }}>
                        {ver.versionLabel || 'v1.0'}
                      </td>
                      <td style={{ padding: '12px 16px', fontWeight: 500 }}>
                        {ver.academicYear} ({ver.semester})
                      </td>
                      <td style={{ padding: '12px 16px' }}>
                        {ver.year || 'CSE'} {ver.section ? `'${ver.section}'` : ''}
                      </td>
                      <td style={{ padding: '12px 16px', color: 'var(--color-on-surface-variant)' }}>
                        {ver.generatedBy || 'Academic Coordinator'}
                      </td>
                      <td style={{ padding: '12px 16px' }}>
                        <Badge
                          variant={
                            ver.status === 'PUBLISHED'
                              ? 'success'
                              : ver.status === 'APPROVED'
                              ? 'primary'
                              : ver.status === 'PENDING_HOD_APPROVAL'
                              ? 'warning'
                              : ver.status === 'REJECTED'
                              ? 'danger'
                              : 'neutral'
                          }
                        >
                          {ver.status}
                        </Badge>
                      </td>
                      <td style={{ padding: '12px 16px', textAlign: 'right' }}>
                        <div style={{ display: 'inline-flex', gap: '6px' }}>
                          {ver.status === 'PENDING_HOD_APPROVAL' && (
                            <>
                              <Button
                                variant="primary"
                                size="sm"
                                disabled={isUpdating}
                                onClick={() => handleTransition(ver._id, 'APPROVED')}
                              >
                                Approve
                              </Button>
                              <Button
                                variant="danger"
                                size="sm"
                                disabled={isUpdating}
                                onClick={() => handleTransition(ver._id, 'REJECTED')}
                              >
                                Reject
                              </Button>
                            </>
                          )}
                          {ver.status === 'APPROVED' && (
                            <Button
                              variant="success"
                              size="sm"
                              disabled={isUpdating}
                              onClick={() => handleTransition(ver._id, 'PUBLISHED')}
                            >
                              Publish
                            </Button>
                          )}
                          {ver.status === 'PUBLISHED' && (
                            <Badge variant="success">Active Live</Badge>
                          )}
                          {ver.status === 'GENERATED' && (
                            <Button
                              variant="secondary"
                              size="sm"
                              disabled={isUpdating}
                              onClick={() => handleTransition(ver._id, 'PENDING_HOD_APPROVAL')}
                            >
                              Submit to HOD
                            </Button>
                          )}
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}
