const TimetableVersion = require('../models/TimetableVersion');
const TimetableSession = require('../models/TimetableSession');
const AcademicContext = require('../models/AcademicContext');
const Faculty = require('../models/Faculty');
const HODFacultyAllocation = require('../models/HODFacultyAllocation');

async function seedTimetable() {
  console.log('[Seed] Seeding published timetable version and faculty session grid...');

  // Locate academic context for III Year CSE Section A
  let context = await AcademicContext.findOne({
    department: 'CSE',
    year: 'III Year',
    section: 'A',
  });

  if (!context) {
    context = await AcademicContext.create({
      academicYear: '2026-27',
      semester: 'Odd Semester',
      department: 'CSE',
      year: 'III Year',
      section: 'A',
      program: 'UG',
      status: 'ACTIVE',
    });
  }

  // Clear existing seeded timetable sessions and versions
  await TimetableSession.deleteMany({});
  await TimetableVersion.deleteMany({});

  const version = await TimetableVersion.create({
    academicYear: '2026-27',
    semester: 'Odd Semester',
    department: 'CSE',
    year: 'III Year',
    section: 'A',
    version: 1,
    versionLabel: 'v1.0 (Official Semester Rollout)',
    status: 'PUBLISHED',
    generatedBy: 'Mr. R. Manikandan (AC)',
    submittedBy: 'Mr. R. Manikandan (AC)',
    approvedBy: 'Dr. T. Rajasekaran (HOD)',
    approvedAt: new Date(),
    publishedAt: new Date(),
    hardConflicts: 0,
    totalScheduledPeriods: 35,
  });

  const sessions = [
    // --- MONDAY ---
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC16',
      courseName: 'Object Oriented Software Engineering',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'MON',
      period: 'P1',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC15',
      courseName: 'Full Stack Development (PBL)',
      facultyId: 'FWL-14',
      facultyName: 'Ms. D. Vinoparkavi',
      day: 'MON',
      period: 'P2',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSX42',
      courseName: 'UI and UX Design (PSE)',
      facultyId: 'FWL-06',
      facultyName: 'Mrs. E. Padma',
      day: 'MON',
      period: 'P3',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC16',
      courseName: 'Object Oriented Software Engineering',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'MON',
      period: 'P4',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC14',
      courseName: 'Principles of Compiler Design',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Manchula',
      day: 'MON',
      period: 'P5',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSX21',
      courseName: 'Fundamentals of Cryptography and Network Security (PSE)',
      facultyId: 'FWL-12',
      facultyName: 'Mrs. K. Eswari',
      day: 'MON',
      period: 'P6',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSS01',
      courseName: 'Library & Online Certification',
      facultyId: 'FWL-06',
      facultyName: 'Mrs. E. Padma',
      day: 'MON',
      period: 'P7',
      room: 'Digital Library',
      sessionType: 'OTHER',
      duration: 1,
    },

    // --- TUESDAY ---
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC14',
      courseName: 'Principles of Compiler Design',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Manchula',
      day: 'TUE',
      period: 'P1',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSX21',
      courseName: 'Fundamentals of Cryptography and Network Security (PSE)',
      facultyId: 'FWL-12',
      facultyName: 'Mrs. K. Eswari',
      day: 'TUE',
      period: 'P2',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC15',
      courseName: 'Full Stack Development (PBL)',
      facultyId: 'FWL-14',
      facultyName: 'Ms. D. Vinoparkavi',
      day: 'TUE',
      period: 'P3',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSM01',
      courseName: 'Mentor Proctoring & Interaction',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'TUE',
      period: 'P4',
      room: 'LH-101',
      sessionType: 'SAS',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSP10',
      courseName: 'Object Oriented Software Engineering Laboratory',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'TUE',
      period: 'P5',
      room: 'Systems Lab 2',
      sessionType: 'LAB',
      duration: 3,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSP10',
      courseName: 'Object Oriented Software Engineering Laboratory',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'TUE',
      period: 'P6',
      room: 'Systems Lab 2',
      sessionType: 'LAB',
      duration: 3,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSP10',
      courseName: 'Object Oriented Software Engineering Laboratory',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'TUE',
      period: 'P7',
      room: 'Systems Lab 2',
      sessionType: 'LAB',
      duration: 3,
    },

    // --- WEDNESDAY ---
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSX42',
      courseName: 'UI and UX Design (PSE)',
      facultyId: 'FWL-06',
      facultyName: 'Mrs. E. Padma',
      day: 'WED',
      period: 'P1',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC16',
      courseName: 'Object Oriented Software Engineering',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'WED',
      period: 'P2',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSP09',
      courseName: 'Full Stack Development Laboratory',
      facultyId: 'FWL-14',
      facultyName: 'Ms. D. Vinoparkavi',
      day: 'WED',
      period: 'P3',
      room: 'Web Tech Lab',
      sessionType: 'LAB',
      duration: 2,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSP09',
      courseName: 'Full Stack Development Laboratory',
      facultyId: 'FWL-14',
      facultyName: 'Ms. D. Vinoparkavi',
      day: 'WED',
      period: 'P4',
      room: 'Web Tech Lab',
      sessionType: 'LAB',
      duration: 2,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC14',
      courseName: 'Principles of Compiler Design',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Manchula',
      day: 'WED',
      period: 'P5',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSX21',
      courseName: 'Fundamentals of Cryptography and Network Security (PSE)',
      facultyId: 'FWL-12',
      facultyName: 'Mrs. K. Eswari',
      day: 'WED',
      period: 'P6',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CST01',
      courseName: 'Technical Seminar & Communication',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Manchula',
      day: 'WED',
      period: 'P7',
      room: 'Seminar Hall 2',
      sessionType: 'TUTORIAL',
      duration: 1,
    },

    // --- THURSDAY ---
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSP04',
      courseName: 'Algorithms Laboratory',
      facultyId: 'FWL-06',
      facultyName: 'Mrs. E. Padma',
      day: 'THU',
      period: 'P1',
      room: 'Algorithms Lab',
      sessionType: 'LAB',
      duration: 2,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSP04',
      courseName: 'Algorithms Laboratory',
      facultyId: 'FWL-06',
      facultyName: 'Mrs. E. Padma',
      day: 'THU',
      period: 'P2',
      room: 'Algorithms Lab',
      sessionType: 'LAB',
      duration: 2,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC16',
      courseName: 'Object Oriented Software Engineering',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'THU',
      period: 'P3',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSX42',
      courseName: 'UI and UX Design (PSE)',
      facultyId: 'FWL-06',
      facultyName: 'Mrs. E. Padma',
      day: 'THU',
      period: 'P4',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC15',
      courseName: 'Full Stack Development (PBL)',
      facultyId: 'FWL-14',
      facultyName: 'Ms. D. Vinoparkavi',
      day: 'THU',
      period: 'P5',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC14',
      courseName: 'Principles of Compiler Design',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Manchula',
      day: 'THU',
      period: 'P6',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSL04',
      courseName: 'Aptitude & Soft Skills Training',
      facultyId: 'FWL-12',
      facultyName: 'Mrs. K. Eswari',
      day: 'THU',
      period: 'P7',
      room: 'LH-101',
      sessionType: 'OTHER',
      duration: 1,
    },

    // --- FRIDAY ---
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC16',
      courseName: 'Object Oriented Software Engineering',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'FRI',
      period: 'P1',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC15',
      courseName: 'Full Stack Development (PBL)',
      facultyId: 'FWL-14',
      facultyName: 'Ms. D. Vinoparkavi',
      day: 'FRI',
      period: 'P2',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSX21',
      courseName: 'Fundamentals of Cryptography and Network Security (PSE)',
      facultyId: 'FWL-12',
      facultyName: 'Mrs. K. Eswari',
      day: 'FRI',
      period: 'P3',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSC14',
      courseName: 'Principles of Compiler Design',
      facultyId: 'FWL-04',
      facultyName: 'Dr. A. Manchula',
      day: 'FRI',
      period: 'P4',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSP01',
      courseName: 'Project Work Phase I',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'FRI',
      period: 'P5',
      room: 'LH-101',
      sessionType: 'PBL',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSX42',
      courseName: 'UI and UX Design (PSE)',
      facultyId: 'FWL-06',
      facultyName: 'Mrs. E. Padma',
      day: 'FRI',
      period: 'P6',
      room: 'LH-101',
      sessionType: 'THEORY',
      duration: 1,
    },
    {
      timetableVersionId: version._id,
      academicContextId: context._id,
      courseCode: '22CSS02',
      courseName: 'Sports & Extracurriculars',
      facultyId: 'FWL-03',
      facultyName: 'Dr. S. Karpusamy',
      day: 'FRI',
      period: 'P7',
      room: 'Sports Complex',
      sessionType: 'OTHER',
      duration: 1,
    },
  ];

  const inserted = await TimetableSession.insertMany(sessions);
  console.log(`[Seed] Successfully seeded ${inserted.length} timetable sessions across Mon-Fri.`);

  // Seed authoritative HOD faculty allocations for all scheduled curriculum courses
  await HODFacultyAllocation.deleteMany({});
  const hodAllocsMap = new Map();

  sessions.forEach((s) => {
    if (s.courseCode && !s.courseCode.startsWith('22CSS')) {
      const key = `${s.academicContextId}_${s.courseCode}`;
      if (!hodAllocsMap.has(key)) {
        hodAllocsMap.set(key, {
          academicContextId: s.academicContextId,
          courseCode: s.courseCode,
          courseName: s.courseName,
          facultyId: s.facultyId,
          facultyName: s.facultyName,
          allocationType: s.sessionType === 'LAB' ? 'LAB_PRIMARY' : 'THEORY',
          assignedBy: 'Dr. T. Rajasekaran (HOD)',
          status: 'APPROVED',
        });
      }
    }
  });

  // Also add allocation for II Year A and IV Year A
  const iiYearA = await AcademicContext.findOne({ year: 'II Year', section: 'A' });
  if (iiYearA) {
    hodAllocsMap.set(`${iiYearA._id}_22CSC06`, {
      academicContextId: iiYearA._id,
      courseCode: '22CSC06',
      courseName: 'Computer Networks',
      facultyId: 'FWL-02',
      facultyName: 'Dr. B. Paramasivan',
      allocationType: 'THEORY',
      assignedBy: 'Dr. T. Rajasekaran (HOD)',
      status: 'APPROVED',
    });
  }

  const ivYearA = await AcademicContext.findOne({ year: 'IV Year', section: 'A' });
  if (ivYearA) {
    hodAllocsMap.set(`${ivYearA._id}_22CSC21`, {
      academicContextId: ivYearA._id,
      courseCode: '22CSC21',
      courseName: 'Cryptography and Network Security',
      facultyId: 'FWL-01',
      facultyName: 'Dr. M. Bhuvaneswari',
      allocationType: 'THEORY',
      assignedBy: 'Dr. T. Rajasekaran (HOD)',
      status: 'APPROVED',
    });
  }

  const insertedAllocs = await HODFacultyAllocation.insertMany(Array.from(hodAllocsMap.values()));
  console.log(`[Seed] Successfully seeded ${insertedAllocs.length} authoritative HOD faculty allocations.`);

  return { version, sessions: inserted, hodAllocations: insertedAllocs };
}

module.exports = { seedTimetable };
