import React from 'react';
import Card from '../common/Card';
import Input from '../common/Input';
import Select from '../common/Select';
import Badge from '../common/Badge';
import { FACULTY_DESIGNATIONS, DEFAULT_DEPARTMENT } from '../../constants/responsibilityMaster';

export default function FacultyBasicInfoForm({
  formData,
  onChange,
  errors = {},
}) {
  const handleChange = (field, value) => {
    onChange({
      ...formData,
      [field]: value,
    });
  };

  const handleBasicInfoChange = (newInfo) => {
    onChange({
      ...formData,
      title: newInfo.title,
      facultyName: newInfo.facultyName,
      designation: newInfo.designation,
      department: newInfo.department,
      email: newInfo.email,
      phone: newInfo.phone,
      dob: newInfo.dob,
    });
  };

  return (
    <Card
      title="1. Faculty Information"
      action={<Badge variant="primary">Mandatory Section</Badge>}
      style={{ marginBottom: '24px' }}
    >
      <div style={{ marginBottom: '16px' }}>
        <p className="text-muted text-sm" style={{ margin: 0 }}>
          Enter the faculty member's profile details. The institutional Faculty ID (e.g., <code>FWL-28</code>) is automatically generated by the backend server.
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px' }}>
        <Input
          label="Title *"
          id="faculty-title-input"
          placeholder="e.g. Dr., Prof., Mr., Ms."
          value={formData.title || ''}
          onChange={(e) => handleChange('title', e.target.value)}
          error={errors.title}
          required
          icon="🏷️"
          helperText="Academic or courtesy title prefix (required)"
        />

        <Input
          label="Faculty Name *"
          id="faculty-name-input"
          placeholder="e.g. K. Suresh Kumar"
          value={formData.facultyName || ''}
          onChange={(e) => handleChange('facultyName', e.target.value)}
          error={errors.facultyName}
          required
          icon="👤"
          helperText="Full name without title prefix (required)"
        />

        <Input
          label="Date of Birth"
          id="faculty-dob-input"
          type="date"
          value={formData.dob || ''}
          onChange={(e) => handleChange('dob', e.target.value)}
          error={errors.dob}
          icon="📅"
          helperText="Optional: Format: DD-MM-YYYY"
        />

        <Select
          label="Designation"
          id="faculty-designation-select"
          value={formData.designation || ''}
          onChange={(e) => handleChange('designation', e.target.value)}
          options={FACULTY_DESIGNATIONS.map((d) => ({ value: d, label: d }))}
          placeholder="Select academic designation..."
          error={errors.designation}
          icon="🎓"
          helperText="Optional: Academic position/rank"
        />

        <Input
          label="Official Email Address"
          id="faculty-email-input"
          type="email"
          placeholder="e.g. sureshkumar@nec.edu.in"
          value={formData.email || ''}
          onChange={(e) => handleChange('email', e.target.value)}
          error={errors.email}
          icon="✉️"
          helperText="Optional: Must be a valid email format"
        />

        <Input
          label="Contact Phone Number"
          id="faculty-phone-input"
          type="tel"
          placeholder="e.g. 9876543210"
          value={formData.phone || ''}
          onChange={(e) => handleChange('phone', e.target.value)}
          error={errors.phone}
          icon="📞"
          helperText="Optional: 10-digit mobile number"
        />

        <div className="ui-form-group">
          <label className="ui-label">Institutional Clearance / System Role</label>
          <div style={{ display: 'flex', alignItems: 'center', height: '40px', gap: '8px' }}>
            <Badge variant="neutral">FACULTY</Badge>
            <span className="text-xs text-muted">Auto-assigned institutional role</span>
          </div>
        </div>
      </div>
    </Card>
  );
}
